- cls/SourceControl/Git/Extension.cls
- cls/SourceControl/Git/Settings.cls
- cls/SourceControl/Git/StreamServer.cls
- cls/SourceControl/Git/Utils.cls
- csp/gitprojectsettings.csp
- git-webui/release/share/git-webui/webui/index.html
- git-webui/src/share/git-webui/webui/index.html
- module.xml
Support/use localization to get display names in menus
Incorporate Ens_SourceControl.js
Fixes #53, #54
> Improvements for portal-based interoperability editors

- cls/SourceControl/Git/Extension.cls
- cls/SourceControl/Git/Utils.cls
> Implement OnBeforeTimestamp in extension

- git-webui/release/share/git-webui/webui/css/git-webui.css
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
A refresh button is now added to prune refs to deleted remotes.
> Prune remote branches

- README.md
> Depends on git 2.31.0+

- cls/SourceControl/Git/Settings.cls
> Creates namespace temp directory from settings if it does not already exist

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
This reloads page if the login has expired. It only does so after a POST request to the backend to run a git command, because the frontend doesn't really communicate with the backend otherwise. It's not a perfect solution, but I can't think of a better one.
Note: Depends on the PR #83 mainly for testing purposes. 
Closes #42
> Reload page on login expiration

- README.md
> Updated README with OpenSSH requirement

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
If the branch is already up-to-date then we now display a proper message to the user instead of none at all.
> Merge minor UX improvements

- git-webui/release/share/git-webui/webui/css/git-webui.css
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/css/git-webui.less
- git-webui/src/share/git-webui/webui/js/git-webui.js
Issue:
Changes background color to proper dark grey for the new branch name on the Web UI so that the user can see what they're typing a bit better.
> Background color fix

- csp/gitprojectsettings.csp
- git-webui/release/share/git-webui/webui/css/git-webui.css
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/css/git-webui.less
Fixed some IE bugs. 
1. The polyfill for `Array.prototype.fill()` wasn't being served for some reason so I just rewrote the code to not need it. 
2.  Removed  an  unnecessary  horizontal  scrollbar.
> Minor webui improvements

- csp/gitprojectsettings.csp
> Replaced wrong text for % class form input

- cls/SourceControl/Git/Change.cls
- cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
- cls/SourceControl/Git/Utils.cls
- inc/SourceControl/Git.inc
1. Added `!` at the starting of every `write`. 
2. Created a macro to add a new line if the size of the stream passed as an argument is >0.
Closes #129
> Add new lines to output wherever necessary

- git-webui/release/share/git-webui/webui/css/git-webui.css
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/css/git-webui.less
- git-webui/src/share/git-webui/webui/js/git-webui.js
1. The modal size was not being appended correctly while creating the popup for the sidebar.
2. The branch buttons in the modal had a border around them and a light grey background color. I removed both of them.
Closes #144
> Sidebar modal fix

- cls/SourceControl/Git/Utils.cls
- csp/gitprojectsettings.csp
- test/UnitTest/SourceControl/Git/NameToInternalNameTest.cls
Reverts intersystems/git-source-control#168
> Revert "Separate NoFolders mappings"

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> Directories are expanded into their files in the workspace

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> Create entry for first commit, clearer loop break condition, remove commented code blocks

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
- module.xml
Hi,
Just a small patch to show UTF-8 accents in commit messages...
Regards,
Patrick
> Handle UTF-8 characters in git commit messages

- CHANGELOG.md
- cls/SourceControl/Git/Change.cls
- cls/SourceControl/Git/PackageManagerContext.cls
- cls/SourceControl/Git/Utils.cls
- module.xml
Fixes #31 
This is still a WIP, but putting it up for comment in advance
> Support pre-IRIS installation

- CHANGELOG.md
- README.md
- cls/SourceControl/Git/Settings.cls
- cls/SourceControl/Git/Utils.cls
- module.xml
- test/UnitTest/SourceControl/Git/AddRemove.cls
- test/UnitTest/SourceControl/Git/Initialization.cls
- test/UnitTest/SourceControl/Git/NameToInternalNameTest.cls
- Installation adds a Management Portal favorite for all users (#209)
- Improved configuration and defaults to simplify initial configuration (#213)
- Added documentation improvements and warning messages around misconfiguration cases (#207, #204)
> Improvements to configuration and initialization 

- CHANGELOG.md
- cls/SourceControl/Git/WebUIDriver.cls
- csp/gitprojectsettings.csp
- module.xml
This "just works" thanks to %CSP.StudioTemplateSuper.
Fixes #230
> Consistently use Namespace instead of NSpace

- CHANGELOG.md
- csp/gitprojectsettings.csp
> Fix adding mappings through the settings web UI

- CHANGELOG.md
- cls/SourceControl/Git/Extension.cls
- cls/SourceControl/Git/Utils.cls
- module.xml
Added `Unconfigure` phase to `module.xml` and defined the method to reset the `SourceControlClass`
> Reset source control class

- CHANGELOG.md
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> Stash in web UI includes untracked files

- CHANGELOG.md
- cls/SourceControl/Git/PackageManagerContext.cls
- module.xml
> Fix for git submodules support

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
Git commit command is now all on one line.
> Fixed issue where commit details are cut off

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
fixes #377 The links sent back from remote repo for pull requests are now html links
> Pull request link after pushing now renders as HTML link in webui

- cls/SourceControl/Git/Utils.cls
- cls/_zpkg/isc/sc/git/Socket.cls
The pull preview actually outputs the preview now, and pull/merge commands now sync modifications as well as adds/deletes.
> Fix issues with pulling changes with pull.csp page

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
Fixes #401 
The button to cancel actions on other users' files now closes the modal and doesn't perform the action
> modal cancel button works

- cls/SourceControl/Git/Extension.cls
- cls/SourceControl/Git/File.cls
- cls/SourceControl/Git/Settings.cls
- cls/SourceControl/Git/Utils.cls
Moving my work in progress on the production decomposition project from a fork into a branch on the main repository.
> Production decomposition work in progress

- CHANGELOG.md
- csp/gitprojectsettings.csp
- csp/webuidriver.csp
> Fix error popups in Studio on 2024.1+

- CHANGELOG.md
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> tooltip now shows user who made uncommitted change

- cls/SourceControl/Git/Settings.cls
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
Fixes #339 and another bug with new repositories where the empty initial commit wasn't occurring
> Webui new repo bugs

- CHANGELOG.md
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
double quotes are turned into single quotes
> Double quotes allowed in commit and amend messages

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
> Resolved bug causing pulls to fail

- docs/testing.md
> Add pre-release testing document

- .github/workflows/main.yml
No changelog because this is just tech debt.
Test coverage reporting via codecov.io is working again.
> Fix coverage

- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
Web UI was broken in Studio by b0ff1430
> Fix for JS syntax error preventing use of Web UI with Studio

- CHANGELOG.md
- cls/SourceControl/Git/Change.cls
- cls/SourceControl/Git/DiscardState.cls
- cls/SourceControl/Git/Utils.cls
> Changed dynamic SQL to embedded SQL

- CHANGELOG.md
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> Fix other user's changes display username in workspace view

- CHANGELOG.md
- csp/gitprojectsettings.csp
Since saving causes us to move up to the top of the page, added a success banner at the top which will be visible
fixes #550
> Added settings success banner

- CHANGELOG.md
- cls/SourceControl/Git/Extension.cls
> Add force export condition

- CHANGELOG.md
- git-webui/release/share/git-webui/webui/js/git-webui.js
- git-webui/src/share/git-webui/webui/js/git-webui.js
> Fix GitUI branch regex

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
- csp/gitprojectsettings.csp
fix #357 
We seem to be doing a pretty good job of this already, fixed all of the places I could find
> Remove windows style paths as defaults

- README.md
Also reworded a little bit; the Studio pieces were weird.
Fixes #386
> docs: secret sneaky auto-refresh checkbox

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
Fix #251 
Issue was ImportCSPFile attempting to delete a file that did not exist
> Fix CSP imports

- README.md
- docs/baselining.md
> Add documentation for baselining process

- CHANGELOG.md
- cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
> Fix deleting files on import

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
> Fix lookup tables

- CHANGELOG.md
- cls/SourceControl/Git/Production.cls
> Fix parsing PTD items on network drive

- CHANGELOG.md
Document fixes in #782 in the changelog.
> Changelog for fixes in #782

- CHANGELOG.md
- module.xml
Update version number in changelog and module.
> Bookkeeping for 2.12.1 patch

- CHANGELOG.md
- module.xml
Planning to release these fixes now as a patch version 2.12.2
> Update module and changelog for patch version

- CHANGELOG.md
- module.xml
Fixed changelog which was made inaccurate because #828 didn't make it into the latest release.
> Fix changelog and module.xml for next version

- CHANGELOG.md
- cls/SourceControl/Git/Utils.cls
- module.xml
> Compile CSP pages for Git UIs after installation
