intersystems/git-source-control

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

The merge-diff format is now separate instead of the default combined. This does not affect regular commits. Turned out to be a much simpler fix than I initially expected.

Commit Explorer view now works for merge commits as well.

---

git-webui/release/share/git-webui/webui/css/git-webui.css

I think this was probably an artifact of the VSCode "random undo" bug - I should have installed from the PR branch.
Re-running grunt release fixed this.

Add missing bracket in release git-webui.css

---

git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/css/git-webui.less
git-webui/src/share/git-webui/webui/js/git-webui.js

The refresh button now rotates while we wait for the git fetch --prune to run

Rotate refresh button

---

cls/SourceControl/Git/API.cls
cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Modification.cls
cls/SourceControl/Git/PackageManagerContext.cls
cls/SourceControl/Git/PullEventHandler.cls
cls/SourceControl/Git/PullEventHandler/Default.cls
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/PullEventHandler/PackageManager.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/StreamServer.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls

Used AppS.CodeTidy with the new tab setting set to 4 spaces.

Standardize code style

---

git-webui/release/share/git-webui/webui/js/git-webui.js

Adds accordion buttons to merge local or remote branches with current branch. 
Checks if automatic merge is possible as described in the issue. 
Performs merge if automatic merge is possible.
Displays proper error and success messages

Merge functionality

---

cls/SourceControl/Git/Utils.cls

Removing from source control now works as expected. We still don't seem to support removing individual files from Source Control in cases where entire packages were added to source control. A fix for this would be to add individual files to source control instead of the package. Not sure how this would change things though. 
This PR closes #76 :
- Adds a new parameter NotMySlash
- A method to fix slashes in a filepath for the OS
- Finds the files that are being tracked according to mappings. So it now does not look for only XML files. Should that be the default? 
- Deletes files that are no longer in source control (same as before)
- Removes files from git tracking
Please review this more extensively than usual. I might have missed some things because of my limited ObjectScript knowledge.

Removing from source control now works

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

1. Default parameters don't work on IE. Fixed that by setting the variable if it is `undefined`.
2. `self.cancel()` was not being called in `cancelByAvailability()`, so changes that did not need a confirmation from the user did not get cancelled.

compatibility fix for IE + minor bugfix

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

String.substr() is deprecated and substring() works a little differently

---

README.md
cls/SourceControl/Git/Utils.cls

Automatically stage any changes to sc-list.txt and note in README

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Currently the working copy is not updated so it can be a little confusing to see the files you stashed still in the working copy.

Automatically refresh the list of files in Working Copy after stashing

---

cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

When nested folder structure is not enabled, files are now mapped into folders corresponding to their extension. No further folder nesting occurs.
To enable this behavior, turn off the folder switch in the settings. Note, this only works for a universal file type mapping. So the coverage must be *
This PR also fixes the bug where some file extensions were being changed to `.cls` incorrectly.
Closes #92 and #93

Preserve filenames for AbstractDocuments

---

cls/SourceControl/Git/Change.cls

Minor thing
In RemoveUncommitted, need to add line break after output as output is not cleared between subsequent actions - which is fine and likely preferred - but makes for a confusing run on sentence.
exporting new version of MyTable.lut to /hfs/sys/git/IRISHealth/INTGBUS/lut/MyTable.lut
/hfs/sys/git/IRISHealth/INTGBUS/lut/MyTable.lut removed from uncommitted list <Should be line break here> exporting new version of MySchema_2.5.1.hl7 to /hfs/sys/git/IRISHealth/INTGBUS/hl7/MySchema_2/5/1.hl7
/hfs/sys/git/IRISHealth/INTGBUS/hl7/MySchema_2/5/1.hl7 removed from uncommitted list
Note also the schema is still splitting into separate files on the dots. I thought this was fixed but may have misunderstood. Still looking at this part.

Add Line break in Output window

---

git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/css/git-webui.less
git-webui/src/share/git-webui/webui/js/git-webui.js

Closes #107 . The UI calls the `uncommitted` API and checks if any of the modified files were changed by a different user than the one signed in. 
- If yes, then a dialog pops us asking the user to warn the user that they will be carrying over those changes as well and confirms that the user wants to go ahead with the branch switch. 
- If no, then checkout proceeds as before.
Works for local and remote branch checkout, and branch creation. 
Note: There is a lot of repeated code/code structure in this PR. I first tried to wrap the popup creation in a different function but the if-else blocks that execute the appropriate action have to be different for different use cases. So then I just put in the code to determine the flag variable into a different function but because JS is asynchronous, …

Uncommitted check on checkout

---

cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

1. Configuring this is also possible from the Settings page. (The `Configure()` method picks up all properties of the class, so I didn't need to do anything special for that)
2. By default, "%" is replaced with an empty string (same as it is now, so it shouldn't break anything).
Closes #111

Configurability for how class names are changed on export

---

cls/SourceControl/Git/WebUIDriver.cls
csp/gitprojectsettings.csp

Checks the request URL for a prefix and prepends it to the base URL if it exists.
Closes #121

Check for a URL prefix and add it

---

cls/SourceControl/Git/Utils.cls

1. Setting `IgnorePercent` to 0 so that the `InternalName` of a percent class is not empty when adding it to source control. Closes #134 
2. Fixing an invalid global reference in the `Name()` method used to compute the `FullExternalName()` of files. We were getting incorrect paths for some files before. Closes #135 (could this also be the issue in #130?)

Minor bug fixes in utils

---

cls/SourceControl/Git/Utils.cls

The `GitStatus()` method does not filter out cases where the external name is an empty string, and leaves in some leading whitespace in the type of change. I fixed these issues.

Strip leading whitespace to type of change, filter out empty rows

---

git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/css/git-webui.less
git-webui/src/share/git-webui/webui/js/git-webui.js

I think the issue was happening because, on load, we were trying to display the log of ref before all the async git requests were finished but I am not a 100% sure. 
Moving the `selectRef` to after we finish building the sidebar seems to do the trick though. 
Closes #141

Graph fill fix

---

cls/SourceControl/Git/Utils.cls

This (a) doesn't work and (b) breaks the package manager context detection. (Discovered this running with latest git-source-control on a new instance using multiple package manager-enabled projects.)
Fixes #159 159

Don't try to source control .ZPM docs

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

The workspace now displays a diff of untracked files as well. We need to jump through some hoops to get the diff of untracked files because of some weird design decisions in git. 
Closes #142

Display diff of untracked files

---

cls/SourceControl/Git/Change.cls
inc/SourceControl/Git.inc

If you do commits from the WebUI, the Uncommitted queue keeps accumulating records of changed files which don't get cleared out. This way, there is a way to clear out old changes that have been committed but their records haven't been removed. 
Ideally we want to remove the record when the change is committed though. 
Closes #155

In RefreshUncommitted(), remove item from uncommitted queue if there is no change according to git

---

cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/Utils.cls
inc/SourceControl/Git.inc

We also remove the file from the tracking global if we find that it was deleted while doing an import. Closes #152

Remove deleted file from global

---

cls/SourceControl/Git/Utils.cls
test/UnitTest/SourceControl/Git/NameTest.cls

1. Added test cases for the `Name()` method
2. Added granularity in the way mappings work as described in #173 
Closes #154 and closes #173

Unit tests for Name() and Add granularity for NoFolders mappings

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

After CSP session expires and the user clicks the settings button in the WebUI, we go to the login screen and then route to the settings page directly instead of reloading the WebUI.

Route directly to the settings page instead of going back to the WebUI

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

1. Fixed the check for whether the current user edited a certain file. It failed with filenames which had spaces in them because those strings were quoted and the string used for comparison was not.
2. Fixed the way we get a list of files, upon which the selected operation occurs. 
Closes #178

Fix workspace operations for filenames with spaces

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

When all the changes were made by a different user, a minor difference in the way we concatenated string caused all the changes to be stashed before the user confirmed their action. Fixed the issue.

Confirming a stash operation now works properly

---

cls/SourceControl/Git/Utils.cls

Changed the default behavior of export to not export a file if there no matching mapping found.

Don't export if there is no mapping

---

cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/WebUIDriver.cls

Updated `RefreshUncommitted()` to also add record to the uncommitted queue when appropriate. Also called it in a few places to make sure the uncommitted queue is always up to date.

Refresh uncommitted

---

cls/SourceControl/Git/Utils.cls

We normalize filenames before adding them to source control. This makes operation more consistent.

Consistent filenames in add

---

cls/SourceControl/Git/Utils.cls
test/UnitTest/SourceControl/Git/NameToInternalNameTest.cls

Closes #198.
The new mapping match method is more robust than the previous one. It is described in detail below. We also provide more detailed explanations on what went wrong when adding a file to source control. 
<br/>
For every mapping we have we can compute a composite score that describes how strong the match is. There are 3 main factors that need to be considered here.
Here we have to check if the path in the `ExternalName` matches the path specified by the mapping.
1. Not a match
2. Path match
We confirm that the extension of the file in the `ExternalName` is the same as the extension in the mapping.
1. Not a match
2. Extension match
Note: There is a possibility that the extension of some files might be different from the one in the mapping. e.g. `.dfi` files might be exported out …

Changed the way we match mappings in NameToInternalName, modified and added new testcases

---

README.md

There are the steps I have used when setting up GitHub deploy keys.

Update README.md with steps on setting up multiple GitHub deploy keys on one machine

---

CHANGELOG.md
cls/SourceControl/Git/PackageManagerContext.cls
cls/SourceControl/Git/Utils.cls

Fixes #217 
Key changes:
- "Import All" will properly recognize new files
- "Import All" and "Export All" apply only to the current package manager context and disregard items outside that context
- "Import All" treats "Other" document types (DFI, LUT, etc.) properly

Various fixes for import/export

---

.github/workflows/main.yml
CHANGELOG.md
test/UnitTest/SourceControl/Git/AddRemove.cls
test/UnitTest/SourceControl/Git/NameToInternalNameTest.cls
test/UnitTest/coverage.list

Fixes #52 (could always do more for unit tests, but this is the first part of the battle).
Also turns out a bit of work is needed to get unit tests running on a container when git-source-control isn't loaded in development mode (vs. on an instance on a Windows machine where it is).

Add build/test/pre-IRIS-package script

---

CHANGELOG.md
README.md
cls/SourceControl/Git/Utils.cls

Improve non-https behavior

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/PackageManagerContext.cls
cls/SourceControl/Git/Utils.cls

Allow various places to change InternalName to the actual InternalName we're working with
Fixes #241

Fix behavior with BPL/DTL editing via Studio

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls

Fixes #243
Solution:
- Wrap references to IRISSYS namespace globals in try/catch
- Duplicate git bin config in local namespace in addition to instance-wide default (doesn't matter for default temp folder because this is saved first time it's configured)

Fix <PROTECT> errors rendering menus

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

Fixes #236 
Solution: Extend %Studio.SourceControl.Base instead of %Studio.Extension.Base
Only implements AddToSourceControl - others should be no-ops for purposes of this extension. (We don't want to automatically commit file-by-file, that seems wrong and would be problematic in other deployment contexts.)

Fix interop deployment

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Otherwise tries to use /root/.config/git/attributes - we need irisusr's profile for things to work right
Fixes #231

Use /SHELL to avoid Linux permissions issues

---

cls/SourceControl/Git/Utils.cls

ZPM reports the installer class via GetOther which was messing up package manager awareness for the git repo root. (Really convoluted how this ended up happening.)
This code is intended for BPL/DTL only so it makes sense to enforce that.
This is a fix to unreleased changes, so not making a note in CHANGELOG.md.

Fix unexpected ZPM impact

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js
module.xml

Resolves #253 
Clicking the Push option will run "git push -u origin <selected branch>".
For the current branch:
For any other branch:

Added push option to local branches in web UI

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #273 
If we pull an add/delete to a file with no internal name, do not add/delete it from server-side source control.

Fix error pulling multiple add/deletes of non-IRIS files

---

git-webui/release/share/git-webui/webui/js/git-webui.js

committed git-webui/release branch

---

cls/SourceControl/Git/Build.cls
git-webui/package-lock.json
git-webui/package.json
module.xml

ZPM load in dev mode will build the javascript application

---

CHANGELOG.md
csp/gitprojectsettings.csp

All the subclasses of `SourceControl.Git.PullEventHandler` visible on the settings UI

Add custom pull handlers

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes #297 
Things old IE doesn't like:
Template literals
Named capture groups
String "includes"

Fix JS bugs in Studio Git WebUI

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/css/git-webui.less
git-webui/src/share/git-webui/webui/js/git-webui.js

Testing Steps:
1. In git-source-control repo, checkout longBranchName branch
```
git checkout longBranchName
```
2. Load git-source-control into the current namespace
```
zpm "load <path to local git-source-control repo>"
```
3. Create a new branch with a long name
```
git branch feature_chg0172358_abcdefghijkl123456789123
git push -u origin feature_chg0172358_abcdefghijkl123456789123
```
(enter passcode for deploy key if prompted)
4. In Management Portal Favorites section, open git-source-control UI 
5. Under Remote Branches of left side navigation bar, click More ...
6. Verify that popup is wide enough to fully display the longest branch name.
7. Delete the branch you created in step 3
```
git push origin -d feature_chg0172358_abcdefghijkl123456789123
```
(enter passcode for deploy key …

Show Longer Branch Name in Web UI's "More ..." View

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

This fixes #264.
Testing Steps:
1. In git-source-control repo, checkout overwrite-server-popup branch
```
git checkout overwrite-server-popup
```
2. In VS Code, click the ObjectScript icon in the left side menu to open ObjectScript Explorer window, click "Choose Server and Namespace" and sign in using InterSystems Server Credentials.
3. Load git-source-control into the current namespace
```
zpm "load <path to local git-source-control repo cloned in step 1>"
```
4. Modify a file you haven't overwritten on server
5. Save the file you modified in step 3. Verify that "Failed to import" VS Code popup shows up on the first time you modify and save the file.
6. Click "Overwrite on Server"
7. Modify file from step 3 and save the file. Verify that "Failed to import" VS Code popup no longer shows …

Don't show Failed to Import popup after overwriting the file on server once

---

cls/SourceControl/Git/Extension.cls

Testing Steps
1. Add a new .cls file in SourceControl.Git over isfs server-side editing.
2. Check that the new file now exists under SourceControl.Git and no error was thrown.

Adding new file over isfs no longer throws "system cannot find the file specified" error

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

This fixes #303 
Testing Steps:
1. In git-source-control repo, checkout noStagingForAdd branch
```
git checkout noStagingForAdd
```
2. Load git-source-control into the current namespace
```
zpm "load <path to local git-source-control repo>"
```
3. Create a new class.
4. Add the class file to source control.
```
git add <path to file>
```
5. In Management Portal Favorites section, open git-source-control UI and click Workspace on the side navigation menu.
6. Verify that the new class you added in step 3 doesn't show up in Working Copy or Staging Area sections. 
7. Modify the class you added in step 3 and save.
8. Verify that the class now shows up in the Working Copy section.
9. Click "Stage" button in Working Copy section.
10. Verify that the class now shows up in the Staging Area section …

Don't automatically stage files added to source control

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

This fixes #295 
Testing Steps:
1. In git-source-control repo, checkout branchNameWithSlash
```
git checkout branchNameWithSlash
```
2. Load git-source-control into the current namespace
```
zpm "load <path to local git-source-control repo>"
```
3. Create a branch with a name containing a slash
```
git checkout -b  feature/chgNNNNNN_some_description
git push --set-upstream origin feature/chgNNNNNN_some_description
```
(enter passcode for deploy key if prompted)
```
git checkout branchNameWithSlash
```
4. In Management Portal Favorites section, open git-source-control UI.
5. Under the Remote Branches section of the side navigation menu, click More ... > origin/feature/chgNNNNNN_some_description > Checkout Branch. Check that "Switched to branch 'feature/chgNNNNNN_some_description'" popup …

Checkout branch name with slash via Web UI no longer fails

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/File.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
csp/webuidriver.csp

Throwing this out there as a draft - more testing is needed (both cross-OS on Windows/Linux AND cross-version with/without /ENV on $zf(-100)) before saying it's good to go.
This address both #315 and #269, as well as some issues I've seen with lag in the WebUI, by the following measures:
* Caching the InternalName/ExternalName (that is, in the DB + on the filesystem) mapping
* Caching results of %Library.RoutineMgr:UserType
* Removing needless calls to %File:NormalizeFilename (which is surprisingly slow)
* Removing /SHELL from $zf(-100) calls as much as possible
* Reducing WebUI calls to RefreshUncommitted and in general putting a 10-second throttle on refreshes of the uncommitted queue (which may be bypassed for things like e.g. commit)
Outcomes for a larger project are:
* Opening a …

Various performance fixes

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

This fixes #304 
Testing Steps:
1. In git-source-control repo, checkout otherDevUsername
```
git checkout otherDevUsername
```
2. Load git-source-control into the current namespace
```
zpm "load <path to local git-source-control repo>"
```
3. In Management Portal, navigate to SourceControl_Git.Change table's Execute Query tab (System Explorer > SQL > Tables > SourceControl_Git.Change).
4. Execute the following Insert query:
```
INSERT INTO SourceControl_Git.Change (Action, ChangedBy, Committed, CommittedTime, CommittedTimeDisplay, InternalName, ItemFile, Name) VALUES ('edit','abcd', '0', '1840-12-31 00:00:01', 'uncommitted', 'SourceControl.Git.TestDelete.CLS', 'C:\Users\abcd\git-source-control\cls\SourceControl\Git\TestDelete.cls','SourceControl.Git.TestDelete.CLS');
```
5. In Management …

Show other developer's username in Web UI's workspace

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/TestDelete.cls
cls/SourceControl/Git/Utils.cls

This fixes #299 , #300 
Testing Steps:
1. Delete a class in a repo.
2. Run
```
w ##class(SourceControl.Git.API).Pull()
```
3. Verify that no error messages (Error # ...) are printed in terminal. Instead, "<name of file deleted in step 1> was not imported into the database and will not be compiled." should be printed in terminal.

Handle file deletion in incremental load PullEventHandler and throw errors (if any) instead of returning Success Status

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/TestDelete.cls
cls/SourceControl/Git/Utils.cls

This fixes #308 
Testing Steps:
1. In Management Portal, add a new web application with name `/slg` and physical path `C:\InterSystems\IRIS1\CSP\slg`.
2. Add a .csp file to `/slg` folder under CSP Files in the IRIS instance namespace that you created `slg` application in.
3. Click on the `/slg` folder, then click Git > Add
4. Verify that no error message pops up and "Added /slg/<csp file name>.csp to source control." was printed in terminal.

Add CSP application to Git

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Recent commits have introduced JavaScript features that are not supported by Internet Explorer and result in errors using the Web UI with Studio, rendering the Web UI unusable. Code using unsupported features has been rewritten (with the assistance of babeljs.io/repl) so that errors no longer occur when used with Studio.

Fixes for JS errors preventing use of Web UI with Studio

---

cls/SourceControl/Git/Utils.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes #322 
This re-implements the behavior in #314 using the appropriate git command rather than filtering out adds in the web UI.

Fix committing add of new file

---

README.md

Documentation for offline installation

---

README.md
docs/menu-items.md

Documented the different git-source-control menu options in a markdown file and linked them into the README.md file

Menu item documentation

---

CHANGELOG.md
cls/SourceControl/Git/PackageManagerContext.cls
cls/SourceControl/Git/Util/Singleton.cls
module.xml

Class names have changed and git-source-control goes under the hood in IPM, so it needs to be adjusted.

Get ready for IPM v0.9.0

---

CHANGELOG.md
cls/SourceControl/Git/API.cls
cls/SourceControl/Git/Utils.cls
test/UnitTest/SourceControl/Git/BaselineExport.cls

Resolves #338 
Baseline export utility for now just includes classes and routines.

Added baseline utility

---

CHANGELOG.md
cls/SourceControl/Git/PullEventHandler.cls
cls/SourceControl/Git/Utils.cls

The new branch property in the PullEventHandler class now defaults to holding the value of the current branch before OnPull() is called.

Issue #351 added branch property to the PullEventHandler class

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls

Files that belong to other Git enabled IPM packages are now skipped when removing files in ##class(SourceControl.Git.Change).RefreshUncommitted().

Issue #317 IPM Multi Developer Setting Issue Resolved

---

cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/File.cls
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/Utils.cls

Not putting anything in changelog as these are bugs in unreleased code.
GetPackageVersion supports zpm <= 0.7.1, IPM 0.9.0+
Fixed possible infinite loop in RefreshUncommitted

Fix recent bugs

---

README.md

Could be removed if #365 is implemented.

Documented existing requirement for SQL privileges

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

Fixes #372
Turns out this was super easy - the names are right in management portal / VSCode now. Both were wrong before because both did something slightly different from what Studio did. (Menu item names are still fine there too, though.)

fix: menu item names in VSCode/SMP

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

Now allows users to configure a default branch to merge from during the sync flow before pushing

Fixes #366 Add merge to sync flow

---

CHANGELOG.md
cls/SourceControl/Git/API.cls
cls/SourceControl/Git/Utils.cls
cls/_zpkg/isc/sc/git/Socket.cls

Anytime a git command occurs that adds or deletes files, IRIS will sync with the changes to the project
Fixes #153

Sync with iris for all local repo changes

---

cls/SourceControl/Git/Util/Buffer.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls

Minor tweaks to fix unreleased bugs.
Specifically, we capture any stray output from SourceControl.Git.Util:RunGitCommandWithInput (it now produces a lot), and we code-generate listing the package version in case SourceControl.Git is package-mapped.

Fix history display, version when mapped

---

cls/SourceControl/Git/Util/Buffer.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
cls/_zpkg/isc/sc/git/Socket.cls

Merge, Pull and Rebase will now use the output of the command itself to drive their synchronization with IRIS. 
ex:
the merge command will output:
> Merge made by the 'ort' strategy. 
> cls/package/newb4.cls | 5 ----- 
> cls/package/newb5.cls | 5 ----- 
> cls/package/newb7.cls | 5 +++++ 
> 3 files changed, 5 insertions(+), 10 deletions(-)
> delete mode 100644 cls/package/newb4.cls 
> delete mode 100644 cls/package/newb5.cls 
> create mode 100644 cls/package/newb7.cls 
In this example, the last 3 lines of the output are used to sync iris with the filesystem

Merge, Pull and Rebase now don't use diff to synchronize file system with IRIS

---

CHANGELOG.md
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

Compile items after Import All

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls

Fixes #365 
Now properly retrieves the list of uncommitted files made by another user

Developer sourcecontrol select privileges

---

CHANGELOG.md
cls/SourceControl/Git/PullEventHandler.cls
cls/SourceControl/Git/Util/ProductionConflictResolver.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes #369 
The body of post requests to /git now send the response body as {command: cmd} instead of just passing the unstructured cmd data. This allows special characters like "&" to be a part of commit messages

POST requests to /git now accept all types of characters in the request body

---

cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js

update uncommitted now removes other user's uncommitted files if they're committed

---

cls/SourceControl/Git/Utils.cls

This is needed if you're not pulling the default branch (which may commonly be the case)

fix: explicitly state branch to pull

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js
module.xml

Use 'substring' instead of 'startsWith' to prevent errors in Studio when performing actions such as refreshing remotes.
'startsWith' is not supported by Internet Explorer.

Fix JavaScript errors in Studio

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes #423 
Git status wraps filenames with spaces in quotation marks, which had been breaking parts of the workspace view.

Fixed workspace list and diff of files with spaces in names

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #404
Fixes #407
Files are auto added to source control (and not staged) and show in the uncommitted queue. This ends up resolving #404 and #407 in one fix.

Fix bugs pertaining to adding files

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

WebUI stash list now shows diff for selected stash item

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/css/git-webui.less
git-webui/src/share/git-webui/webui/js/git-webui.js

fix: brought back amending commits

---

git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fix commit diff view

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

disallows the user from choosing the add menu option on an uncompiled file

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls

Keep iris sync output

---

CHANGELOG.md
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

fixes #437, #433
all commits and amends from webui now run through the "/git-command" endpoint

New array based git API command for webui

---

.github/workflows/main.yml

... because it's failing our CIs otherwise

update to upload-artifact v4

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixed Git web UI prompt to update file list

---

cls/SourceControl/Git/Utils.cls

Fixes #477 
No changelog as this is a fix to an unreleased bug (from #466)

fix: avoid infinite loop

---

CHANGELOG.md
csp/gitprojectsettings.csp
module.xml

Fixed folder settings in mappings to be saved and persist

---

CHANGELOG.md
cls/_zpkg/isc/sc/git/Socket.cls

Fixes an issue where the preview on the pull page would diff the current branch against the remote of the main branch, not the remote of the current branch.

Fix pull preview when not on main branch

---

CHANGELOG.md
cls/SourceControl/Git/API.cls
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js
module.xml

Add alerts when git is too old

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls

Changed prompts in configure from 0/1 to no/yes

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #503 
We now diff the old head with the new head. Before we diffed the remote branch with the new head, which misses all the changes made on the remote branch.

Rebasing from remote loads code changed on the remote

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

After performing a fetch I almost always get an unexpected and seemingly incorrect list of changed files.
The diff is being done with ```..origin``` specifed however (at least on my setup) this only ever results in the diff being done against the main branch and not the remote for the branch that I am actually on, which would be for example a feature branch that was branched from another non-main branch.
Unless I am misunderstanding what the intended result of this diff output is then it seems as though the current branch name should be specified too, for example ```..origin/foo/feature1``` so that the diff is comparing the local ```foo/feature1``` branch with the corresponding remote, this is the diff output that I would expect to see.
git version 2.34.1
IRIS for UNIX (Ubuntu Server LTS …

After a fetch perform a diff against the remote of the current branch

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

The current way of handling truncated class names from git pull seems to have two major flaws:
1. It is possible for truncated class names to fail to be expanded if the repository directory structure does not align with class packages
2. When this failure occurs and no possible classes are found, there is no warning generated
For example if the repository has the following base directory structure:
```/foo/bar/``` and contains class ```A.B.C``` stored on disk as ```A/B/C.cls``` (where foo and bar have no relation to any class package names)
then git pull may provide truncated output such as the following:
```.../bar/A/B/C.cls```
```ExpandClasses``` will try and fail to find a class named ```bar.A.B.C``` with no warning generated, the class silently fails to import.
```ExpandClasses``` has …

Improve handling of truncated class names from git pull

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

This is intended as a hopefully superior and simpler alternative to #515 to address the same issue, though only for git pull for now. Files are not always able to be reliably imported when their names are truncated in the git pull stats summary.
The truncated git pull stat summary output is no longer used and diff output is used instead. This should allow all file types to be handled without requiring any new or custom IRIS logic. The diff is performed after the git pull to avoid a potential double fetch and also a potential race condition if the remote changes between the diff and pull taking place.
Also indirectly addresses, for pulls only, the following likely unreported/unknown issues associated with the truncated name expansion logic that I have discovered in recent days, by no …

When performing a pull, sync IRIS with repository changes using diff output rather than command output

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

Calling this a bug fix because allegedly it already worked (though it didn't really)
Fixes #472 the best we can with current IRIS tooling - the menu now looks like:
(note: this requires BES248 / DP-432719 which doesn't go too far back)

fix: actually include branch in status menu item

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Utils.cls
docs/menu-items.md
module.xml

Add **Push to remote branch (Force)** to the menu, allowing an expert mode user to perform ```git push --force```
The user is prompted with a warning and to confirm that they want to do this.
The motivation for this is that a basic mode user is capable of indirectly performing a force push via the **Sync** option, potentially without even realising or understanding that they are doing so. An expert mode user should be able to do the same with intent but currently has no option available outside of manually interacting with the local repository.

Add an option to allow git push --force to be performed in expert mode

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
csp/sync.csp
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

no Commits on default merge branch in basic mode

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls

Added git path interpretation

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Added pruning to fetch calls

---

CHANGELOG.md
csp/sync.csp

Add alert when other users have unstaged changes

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #549, #539
@isc-tleavitt Right now this throws an error (so that user is aware that checkout failed). Is there a better way to show an alert on the management portal / vscode / studio? (This happens on "AfterUserAction" so we have no access to the "Target" functionality of %Studio.SourceControl.Base.

Fixed checking out non-existent branch

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes #406 
This just removes the inaccurate placeholder text about the limit instead of actually enforcing a limit. I feel the commit input being a single line instead of a textarea is enough of a nudge that a commit message should be short and sweet.

Placeholder text on commit input no longer promises a length limit

---

README.md
docs/hcc.md
docs/testing.md

Resolves #489 
This commit changed the behavior so that when a new item is created in IRIS, it is automatically added to source control: https://github.com/intersystems/git-source-control/commit/212b988190e5df2326bd9bcbb99bd70f36b32c00
I don't think this needs to be called out explicitly in documentation at this point, but I've updated the testing plan to reflect it and made some tweaks to the wording in the other documentation.

Clarify documentation about adding items to source control

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

fix: report errors creating new branches

---

CHANGELOG.md
cls/SourceControl/Git/Util/ProductionConflictResolver.cls
test/UnitTest/SourceControl/Git/ProductionConflictResolve.cls

fix: production conflict auto-resolve works again

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls

Suppress editing of locked files

---

cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls

Fixes #592
This is a minor regression in unreleased code, so not bothering with a changelog entry. Also added consistent checking of %gitSCOutputFlag - we've been getting some duplicated logs in Pull because of this

fix: logging issues

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls
csp/gitprojectsettings.csp

fix root repo wording

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fix diffview

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #611 (Caused by change in #573)
DefaultTemp() is only used in DefaultTempFolder()

Fix tempfolder

---

CHANGELOG.md
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Also tidied up clearing of the diff view - this might have been a regression in this release?
Fixes #609

fix: tidy up git command output parsing

---

CHANGELOG.md
cls/SourceControl/Git/WebUIDriver.cls
module.xml

Fix Unicode encoding of Git commands from web UI

---

CHANGELOG.md
cls/SourceControl/Git/API.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls

Fix git issue

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js
module.xml

Added searchbar

---

CHANGELOG.md
README.md
cls/SourceControl/Git/Utils.cls
test/UnitTest/SourceControl/Git/NameTest.cls
test/UnitTest/SourceControl/Git/NameToInternalNameTest.cls

Parameter expansion of environment name in mapping directory

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/css/git-webui.css
git-webui/src/share/git-webui/webui/css/git-webui.less

Fixed studio issues

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Util/Production.cls
cls/SourceControl/Git/Utils.cls
docs/production-decomposition.md
docs/testing.md
module.xml

Add export production option to menu for productions

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

fix push button not appearing

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls
cls/SourceControl/Git/WebUIDriver.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Popping from stash

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls
module.xml

Commit settings

---

CHANGELOG.md
cls/SourceControl/Git/DiscardState.cls
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fix Discard of deleted files

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js
module.xml

Added revert / reset Head

---

CHANGELOG.md
cls/SourceControl/Git/DeploymentLog.cls
cls/SourceControl/Git/PullEventHandler.cls
cls/SourceControl/Git/Utils.cls

Resolves #690 
Prior to this change we were calling ImportItem() twice for every item changed by a Git operation. Once through AddToServerSideSourceControl, and once through the pull event handler. This made every Git operation changing productions twice as long as it needed to be. This was only an issue for production items because other items have a timestamp from %RoutineMgr that lets us skip the import if the item is up to date in IRIS.
Also adds a separate table that logs deployments into IRIS through the pull event handler.

Improvements to deployment of production items

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
test/UnitTest/SourceControl/Git/ProductionDecomposition.cls

Closes #701 
- Fix an error when there is a leftover entry in the Git items cache for the undecomposed production class
- Removes Add to / Remove From Source Control options from menu for decomposed production since they do nothing

Fix errors with decomposed production with invalid cache entries

---

CHANGELOG.md
cls/SourceControl/Git/PullEventHandler/PackageManager.cls
cls/SourceControl/Git/PullEventHandler/PackageManagerReload.cls

Add IPM event handler that does an uninstall

---

CHANGELOG.md
cls/SourceControl/Git/Production.cls

Small fix that makes it safe to edit productions through the new interoperability UI with production decomposition. Edits from the new UI will be treated like edits from the IDE, which means:
- it is read-only unless the "Decomposed Productions Allow IDE" setting is enabled
- you are locked from editing any item in the production if a different user has checked out any item on the production.

Production decomposition with new interoperability editor

---

CHANGELOG.md
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Responsive stash

---

docs/testing.md

Updated docs

---

CHANGELOG.md
cls/SourceControl/Git/Extension.cls
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

New toggle for "lock branch" to prevent branch switching for namespace.

Pull request for Issue 709 add locking branch to settings

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Do not try to import settings file if repo directory does not exist

---

cls/SourceControl/Git/Utils.cls

Related to #734 
The fix from #737 made the favorites links appear, but the hyperlink itself did not work because the SMP doesn't expect the URL to be in a $list format. See upstream reference DP-440691.
This fix is tested in both IRIS 2025.1.0 and 2023.1.3.

Git links in favorites now actually work

---

CHANGELOG.md
csp/pull.csp

Resolves #740 
If there are a lot of changes in the pull preview, it can take up the full page. The scrolling behavior with pre tags is not super intuitive. Adding a max height to the preview makes it easier to see the results.

Improve display of preview on pull page

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls

Deletes are no longer removed from the uncommitted queue

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

Fixes #746
Adding, removing, and updating remote now all work on the settings page.
Since settings page only allows changing a single remote, this is now constrained to be the "origin" remote. Previously behavior was undefined if there were multiple remotes.
If remote is defined, we now test connection and display a warning message if it fails.

Improve remote management on settings page

---

CHANGELOG.md
cls/SourceControl/Git/Production.cls
cls/SourceControl/Git/Utils.cls

Fixes to preview load to determine if production decomposition applies

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp
test/UnitTest/SourceControl/Git/NameTest.cls

Mapping configurations may now include the \<namespace\> token. The token will be expanded to the name of the current namespace. This is the first step towards supporting an instance-wide monorepository in which custom code for each namespace is mapped to a different subdirectory.
Resolves #710 and #756

Mappings expand <namespace> parameter

---

cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

Fixes a bug introduced in #768. Also, behavior is more consistent if changing git repo root directory and remote at the same time.

Fix settings page remote input if git repo not initialized

---

cls/SourceControl/Git/API.cls
cls/SourceControl/Git/Installer.cls

Suggested in #772 
No changelog needed as there is no functional change.

Add method return type to MapEverywhere

---

csp/gitprojectsettings.csp
git-webui/release/share/git-webui/webui/js/git-webui.js
git-webui/src/share/git-webui/webui/js/git-webui.js

Fixes for the following:
- #775 
- Allow basicMode setting to be changed when settingsUIReadOnly is set
- #776 
- Correct refresh of display after reset/revert, also avoids an error
- #780 
- Do not change remote repo if remoteRepo is not set in settings save request

Fixes for revert/reset error and settingsUIReadOnlly related basicMode/remoteRepo

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes production and other export with unexpected directory casing

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Addresses #783 
First commit re-factors the 'diff after git command' mechanism previously added in #517 so that it can be more generically applied to other Git commands.
Second commit applies it to the checkout command.
Works with Git menu dropdown and with WebUI. The diff that was previously being applied prior to the checkout being performed would fail due to the branch not yet being local at that point in time when checking out a remote branch for the first time.

Sync IRIS with repo changes when switching to a remote branch

---

CHANGELOG.md
cls/SourceControl/Git/Settings/Document.cls

Fixes #794 
Do not return the current time as a timestamp when the settings file has never been imported.
Returning the current time can prevent import of the settings file as it can prevent it from being considered outdated.
The comment of the timestamp message very much suggests to me that returning `""` is the intended behaviour and that `$zdatetime($horolog,3)` is just a description of the format of the timestamp that would be returned if there was one.

Fix initial import of settings file that has yet to be imported

---

cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls

Inspired by work on #807 
- Force import to start with as it was getting forced imported later anyway.
- Stop iterating through files once it has been imported.
- Don't import it a second time.

Improve config file handling in the incremental load pull event handler

---

CHANGELOG.md
cls/SourceControl/Git/Change.cls
cls/SourceControl/Git/Extension.cls

This is another case of what was fixed in #758 
The `GetStatus` method of `SourceControl.Git.Extension` can remove deleted items from the uncommitted queue. This can make the deleted items show up as being owned by an 'undefined' user in the workspace view.
This has occurred for me in both Studio and VS Code.

Do not remove deletes from the uncommitted queue when checking item status

---

CHANGELOG.md
CONTRIBUTING.md
cls/SourceControl/Git/Utils.cls

- Adds new lines to `ExportItem()` to make baselining output more consistent and human readable.
- Make the coding style guidelines a little more explicit.

Fix: Make baselining output more consistent.

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

- Fix (Export All): If a tracked item no longer exists in the namespace, remove internal tracking (#821)
- which allows "Export all" to proceed and complete correctly.
----
I think this is good enough @isc-pbarton , but I'm open to changes if there are other things I didn't consider.

Fix: Export All better handles missing items.

---

CHANGELOG.md
cls/SourceControl/Git/Production.cls

Preview load to determine if class is production no longer overwrites class

---

CHANGELOG.md
cls/SourceControl/Git/PackageManagerContext.cls
cls/SourceControl/Git/Utils.cls
test/UnitTest/SourceControl/Git/ImportAll.cls

Fixed deployment of CSP files

---

cls/SourceControl/Git/Utils.cls
docs/menu-items.md

Document previously undocumented behaviors for "Basic" mode for:
- "Create new branch"
- Call out the fact that "Basic" mode first pulls the latest "Default Merge Branch".
- Sync
- Only available in "Basic" mode
- Attempts a `rebase` after synchronizing current branch with remote
- Disallows commits to "Default Merge Branch"
- Commits ALL staged files.

Update documentation for menu item behaviors in "Basic" Mode

---

CHANGELOG.md
cls/SourceControl/Git/PullEventHandler/IncrementalLoad.cls
cls/SourceControl/Git/Utils.cls

Fixes #848 
Gracefully handle `filename` or `item` being empty strings inside `##class(SourceControl.Git.PullEventHandler.IncrementalLoad).DeleteFile()`
Commit 7d52f33d0e2793492352c061d213e57c8c878cd4 causes `filename` to be an empty string more readily. Which results in the first part of the if statement being executed, if `item` is an empty string too then `##class(SourceControl.Git.Utils).RemoveRoutineTSH` will throw an exception and cause the pull to fail.
As described in fixed issue, was observed with an .xsd file that was present in a Git repo and then deleted. Pull would fail when handling the deletion of this file that had no external or internal name.

Fix pull failure when deleted items have no internal or external name

---

CHANGELOG.md
csp/gitprojectsettings.csp
module.xml

Settings page has option to lock/unlock namespace for edits

---

CHANGELOG.md
cls/SourceControl/Git/File.cls

Fixes #864 (for HL7 files too)
`$system.OBJ.Load` is able to load CLS and INC files to determine their internal name. However it is not able to load the HL7 and LUT files exported by Embedded Git. These are XML files with the internal name readily available within, make an attempt to parse the file and get the internal name.
This will help avoid situations such as HL7 or LUT files being introduced at the same time as their Embedded Git mappings where the internal name was previously not able to be determined due to the mappings getting loaded in later and resulting in them not being loaded at all after a pull.
These four file types are the only types that I work with, other types may have similar issues and aren't addressed here.

Attempt to parse HL7 and LUT files to determine their internal name

---

CHANGELOG.md
cls/SourceControl/Git/Utils.cls

Fixes #871
Always specify `--set-upstream` when pushing for consistency with Web UI which always sets `-u` (the shorthand equivalent).
Can't think of any reason not to do this and the various ways to push should have consistent behaviour anyway.
The following is the existing Web UI code, for reference:
https://github.com/intersystems/git-source-control/blob/18999e9321201636a219b42922d460ba16a42ca8/git-webui/release/share/git-webui/webui/js/git-webui.js#L935

Always set the remote as the upstream branch when pushing, for consistency with Web UI

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls

Programmatic configuration of settings as part of the public API

---

CHANGELOG.md
cls/SourceControl/Git/Settings.cls
cls/SourceControl/Git/Utils.cls
csp/gitprojectsettings.csp

Resolves #293
A testing plan:
Clone a GitHub repository via SSH with a private key file. Settings page should say "connection successful" under the Remote Repository input.
Create a new config file with contents matching those suggested here: https://docs.github.com/en/authentication/troubleshooting-ssh/using-ssh-over-the-https-port#enabling-ssh-connections-over-https
Set the "Path to SSH Config File" in settings to that file path and save. It should still say "connection successful".
Set the path to a nonexistent file. It should show an error message under the Remote Repository input.
Clear the value. It should say "connection successful" again.

Add setting for SSH client configuration file
